# Generated by Django 2.0.1 on 2018-03-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Candidate', verbose_name='候选人')),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='job.Job', verbose_name='职位')),
            ],
            options={
                'verbose_name': '用户申请职位',
                'verbose_name_plural': '用户申请职位',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Candidate', verbose_name='候选人')),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='job.Job', verbose_name='职位')),
            ],
            options={
                'verbose_name': '用户收藏职位',
                'verbose_name_plural': '用户收藏职位',
            },
        ),
    ]
