# Generated by Django 2.0.1 on 2018-01-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司全称')),
                ('logo', models.FileField(default='default.png', upload_to='')),
                ('site', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=20)),
                ('scale', models.CharField(choices=[('s', '15以下'), ('m', '15-50人'), ('l', '50-150人'), ('xl', '150-500人'), ('xxl', '500人以上')], max_length=20)),
                ('establish_date', models.DateField()),
                ('slogan', models.CharField(max_length=100)),
                ('company_profile', models.TextField(max_length=1000)),
                ('product_profile', models.TextField(max_length=1000)),
                ('welfare', models.CharField(max_length=50)),
            ],
        ),
    ]
