# Generated by Django 2.0.1 on 2018-01-19 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20)),
                ('education', models.CharField(choices=[('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=10)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('specialty', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_role', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('zhihu', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=100)),
                ('personal_site', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('career_work_year', models.IntegerField()),
                ('skill_keywords', models.CharField(max_length=50)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.Careers')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('belong_careers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.Careers')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.Resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.Skills'),
        ),
        migrations.AddField(
            model_name='projectexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='educationexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resume.Resume'),
        ),
    ]
