# Generated by Django 2.0.1 on 2018-03-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='岗位名称')),
                ('work_city', models.CharField(max_length=20, verbose_name='工作城市')),
                ('addrees', models.CharField(max_length=100, verbose_name='具体地址')),
                ('wage', models.FloatField(default=0.0, verbose_name='工资')),
                ('exp_time', models.IntegerField(verbose_name='工作经验')),
                ('job_description', models.TextField(default='', max_length=500, verbose_name='岗位描述')),
                ('job_requirements', models.TextField(default='', max_length=500, verbose_name='岗位要求')),
                ('key_words', models.CharField(default='', max_length=50, verbose_name='岗位关键字')),
                ('is_verify', models.BooleanField(default=False, verbose_name='审核状态')),
                ('edu', models.CharField(choices=[('0', '无限制'), ('1', '专科'), ('2', '本科'), ('3', '硕士'), ('4', '博士')], max_length=10, verbose_name='最低学历要求')),
                ('school', models.CharField(choices=[('0', '无限制'), ('1', '一本'), ('2', '211'), ('3', '985'), ('4', '清北')], max_length=10, verbose_name='院校要求')),
                ('tpye', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='resume.Careers', verbose_name='岗位类型')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
            },
        ),
    ]
